### ISSUE TITLE
Todo Component

### ISSUE THREAD

**Issue by lokesh-patidar** [SunilHooda/silky-cannon-605#3]
- [x] Create the accessory files and folder for todo functionality.
- [x] Create a redux folder and respective files for functionality and state management.
- [x] Make the get request for two endpoints on two different paged and render them on a common page.
