### ISSUE TITLE
Todo Functionality

### ISSUE THREAD

**Issue by lokesh-patidar** [SunilHooda/silky-cannon-605#4]
- [ ] Create an action file and make crud operations there.
- [ ] Create action-types.
- [ ] Create a reducer file and function with an initial state.
