### ISSUE TITLE
Todo Operation-2

### ISSUE THREAD

**Issue by lokesh-patidar** [SunilHooda/silky-cannon-605#5]
- [x] Manage filter and sorting.
- [x] manage sub-tasks and showcase properly.
- [x] Create an edit page.
